# code: language=ansible
- name: Show version
  hosts: cisco
  vars:
    cli:
      username: admin
      password: cisco123
      timeout: 60

  gather_facts: false
  connection: network_cli
  tasks:
    - name: Show version
      ios_config:
        provider: "{{ cli }}"
        lines:
          - show version
      register: print_output
