#! /bin/bash 
sudoUser='ansible'
# Replace 'your_hashed_password_here' with the actual hashed password generated by openssl
hashedPass='$6$j8VkDHZ0DBgfMmkK$7RAUSbFyf6rRNXJYy3Gtqwwf3/8KP/pOgNybZcPa1Gq0hXMwlC.aUvIxnw8ZPmEojV8vd4WrqGfAu0oUdXA8b1'

# Check if user already exists
if id "$sudoUser" &>/dev/null; then
    echo "User $sudoUser already exists."
else
    # Check for Ubuntu
    if grep -qEi "(ubuntu|debian)" /etc/*release; then
        useradd -s /bin/bash -m -G sudo -p "$hashedPass" "$sudoUser"
        echo "User $sudoUser added on Ubuntu."
    # Check for CentOS/RHEL
    elif grep -qEi "(centos|red hat|redhat)" /etc/*release; then
        useradd -s /bin/bash -m -G wheel -p "$hashedPass" "$sudoUser"
        echo "User $sudoUser added on CentOS."
        # add ssh key to authorized_keys
        mkdir -p /home/$sudoUser/.ssh
        touch /home/$sudoUser/.ssh/authorized_keys
        echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB8Abd5A+suKbUWZtv0PCXR3xQW0qOQLgnEktFqkOEFm Ansible" >> /home/$sudoUser/.ssh/authorized_keys
        # fix permissions for authorized_keys
        chmod 700 /home/$sudoUser/.ssh
        chmod 600 /home/$sudoUser/.ssh/authorized_keys
        chown -R $sudoUser:$sudoUser /home/$sudoUser/.ssh

    else
        echo "Unsupported distribution."
    fi
fi