# Installs chkconfig on CentOS hosts. This is a requirement for the Wazuh agent.
- name: Install chkconfig on CentOS hosts
  become: true
  remote_user: ansible
  hosts: all
  tasks:
  - name: Update all dnf packages on CentOS hosts
    ansible.builtin.dnf:
      name: "chkconfig"
      state: latest
    when: ansible_distribution == "CentOS"
