# Check what distro the hosts are running then update all packages
- name: Update all hosts
  become: true
  remote_user: ansible
  hosts: all
  tasks:
  - name: Update all dnf packages on CentOS hosts
    ansible.builtin.dnf:
      name: "*"
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Update all apt packages on Ubuntu hosts
    ansible.builtin.apt:
      name: "*"
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Reboot if required
    reboot:
    when: reboot_required_file.stat.exists == true
