- name: Set authorized keys taken from url
  become: true
  remote_user: ansible
  hosts: all
  tasks:
    - name: Install keys
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: https://github.com/minizaggi.keys