# Kig efter uplink beskrivelse på port
---
- name: Check and Configure Interface
  hosts: A1
  gather_facts: no
  tasks:
    - name: Gather interface information
      cisco.iso.ios_command:
        commands:
          - show interfaces | include ^[0-9]
      register: interface_output

    - name: Check if interface has uplink in description
      set_fact:
        target_interface: "{{ interface_output.stdout_lines | select('regex', 'uplink') | first }}"

    - name: Apply configuration if uplink found
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ target_interface.split(' ')[0] }}"
            description: UPLINK
            mode: trunk
            state: present
        when: target_interface is defined


# Ansible bruger "when" til at udføre en konfig ændring
# Ansible sætter porten i trunk