- name: Install packages on test server
  hosts: testserver.lab.home
  become: yes

  tasks:
  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Install additional packages
    ansible.builtin.apt:
      name:
      - htop
      - iperf3
      - tcpdump
      - whois
      - nmap
      - git
      state: present
