---
interfaces:
  - name: GigabitEthernet1/0/1
    description: uplink-to-R1 
    enabled: true
    # No switchport
    ip: 172.16.1.2
    mask: 255.255.255.252
  - name: GigabitEthernet1/0/23
    description: Downlink-to-A1New
    enabled: true
    mode: trunk
  - name: vlan10
    description: LAN10
    ip: 10.10.10.1
    mask: 255.255.255.0
    enabled: true
  # - name: vlan20
  #   description: LAN20
  #   ip: 10.10.20.1
  #   mask: 255.255.255.0
  #   enabled: true
  # - name: vlan78
  #   description: LAN78
  #   ip: 10.10.78.1
  #   mask: 255.255.255.0
  #   enabled: true