- hosts: all
  gather_facts: no
  tasks:
  - name: Check Interfaces
    cisco.ios.ios_facts:
      gather_subset:
      - interfaces
  - name: Print variables
    ansible.builtin.debug:
      var: ansible_facts
  - name: Create your local file on master node
    ansible.builtin.file:
      path: /home/ansible/ansible/config_output
      owner: ansible
      group: ansible
      mode: '0640'
    delegate_to: localhost

  - name: Print output to file
    ansible.builtin.copy:
      content: "{{command_output.stdout}}"
      dest: /home/ansible/ansible/config_output 
    delegate_to: localhost
    
